# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LZCommonSDK' do

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LZCommonSDK

    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
    pod 'Aspects', '~> 1.4.1'
    #pod 'KeychainItemWrapper', '~> 1.2'

end
